### ISSUE TITLE
Partly Close Positions → MT4

### ISSUE THREAD

**Issue by growersun** [TheSnowGuru/PyTrader-python-mt4-trading-api-connector#2]
Hi, work Partly Close Positions? I'm not see example

**Comment by Branly76** [comment]
Hi,
Partly close position is not in at the moment.
We will add this.

BR

**Comment by growersun** [comment]
but how long to wait?) I wanted to buy a license, without this it is somehow incomplete.

**Comment by Branly76** [comment]
Hi, 

I'm working on it. 
Will be finished today.
Need also to test and adapt documentation.

BR

**Comment by growersun** [comment]
This is good! Thanks for reply.

**Comment by Branly76** [comment]
Hi,

Partial close of position added.

BR
